---

- name: install kde stuff
  ansible.builtin.apt:
    name:
      - gwenview
      - kde-config-flatpak
      - kde-config-gtk-style
      - kde-config-gtk-style-preview
      - kde-plasma-desktop
      - kde-spectacle
      - okular
      - okular-extra-backends
    update_cache: true
    cache_valid_time: 3600
  tags: apt

  become: "{{ kde_become_admin }}"
  become_user: "{{ kde_become_admin_user }}"
