---

- block:

    - name: configure konsole
      ansible.builtin.shell:
        cmd: "kwriteconfig5 --file {{ item.file }} --group {{ item.group }} --key {{ item.key }} {{ item.value }}"
      with_items:
        - file: konsolerc
          group: MainWindow
          key: MenuBar
          value: Disabled
        - file: konsolerc
          group: MainWindow
          key: State
          value: AAAA/wAAAAD9AAAAAQAAAAAAAAAAAAAAAPwCAAAAAvsAAAAiAFEAdQBpAGMAawBDAG8AbQBtAGEAbgBkAHMARABvAGMAawAAAAAA/////wAAAVgBAAAD+wAAABwAUwBTAEgATQBhAG4AYQBnAGUAcgBEAG8AYwBrAAAAAAD/////AAAA3wEAAAMAAAP+AAACKgAAAAQAAAAEAAAACAAAAAj8AAAAAQAAAAIAAAACAAAAFgBtAGEAaQBuAFQAbwBvAGwAQgBhAHIAAAAAAP////8AAAAAAAAAAAAAABwAcwBlAHMAcwBpAG8AbgBUAG8AbwBsAGIAYQByAAAAAQv/////AAAAAAAAAAA=
  become: "{{ kde_become }}"
  become_user: "{{ kde_become_user }}"
