---
env:
  TERM: xterm-256color

font:
  normal:
    family: "Hack Nerd Font"
    style: Regular

  italic:
    family: "Hack Nerd Font"
    style: Italic

  size: 10.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: -1

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upward.
  glyph_offset:
    x: 0
    y: 0

  # If `true`, bold text is drawn using the bright color variants.
  # draw_bold_text_with_bright_colors: false

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
