---
- name: Install networking stuff.
  become: "{{ apt_become }}"
  become_user: "{{ apt_become_user }}"
  block:

    - name: Networking tools
      ansible.builtin.apt:
        name:
          - aria2
          - bind9-dnsutils
          - curl
          - finger
          - iftop
          - iperf3
          - minicom
          - mitmproxy
          - mosquitto-clients
          - mtr
          - nmap
          - smbclient
          - tcpdump
          - whois
        update_cache: true
        cache_valid_time: 3600
      tags: apt

    - name: Ensure sync tools are present
      ansible.builtin.apt:
        name:
          - git-annex
          - nextcloud-desktop
          - syncthing
          - syncthingtray-kde-plasma
        update_cache: true
        cache_valid_time: 3600

    - name: IM
      ansible.builtin.apt:
        name:
          - quassel-client
        update_cache: true
        cache_valid_time: 3600
      tags: apt

    - name: Ensure net-tools is absent
      ansible.builtin.apt:
        name:
          - net-tools
        state: absent
