---

- block:

    - name: Networking tools
      ansible.builtin.apt:
        name:
          - aria2
          - bind9-dnsutils
          - curl
          - finger
          - iftop
          - iperf3
          - mitmproxy
          - mosquitto-clients
          - mtr
          # - nextcloud-desktop
          - nmap
          - smbclient
          - tcpdump
        update_cache: true
        cache_valid_time: 3600
      tags: apt

    - name: IM
      ansible.builtin.apt:
        name:
          - quassel-client
          - telegram-desktop
        update_cache: true
        cache_valid_time: 3600
      tags: apt

    - name: ensure net-tools is absent
      ansible.builtin.apt:
        name:
          - net-tools
        state: absent


  become: "{{ apt_become }}"
  become_user: "{{ apt_become_user }}"
