---

- name: Development stuff
  become: "{{ devel_become }}"
  become_user: "{{ devel_become_user }}"
  block:

    - name: Ensure essential development tools are present
      ansible.builtin.apt:
        name:
          - build-essential
          - pre-commit
          - sqlite3
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure C and C++ tools are present
      ansible.builtin.apt:
        name:
          - clang
          - clang-format
          - clang-tidy
          - clang-tools
          - clangd
          - cmake
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure C and C++ libraries are present
      ansible.builtin.apt:
        name:
          - libbluetooth-dev
          - libeigen3-dev
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure Python tools are present
      ansible.builtin.apt:
        name:
          - black
          - cookiecutter
          - flake8
          - isort
          - mypy
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure rust stuff is present
      ansible.builtin.apt:
        name:
          - cargo
          - rustc
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure go stuff is present
      ansible.builtin.apt:
        name:
          - golang
          - gopls
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure yaml stuff is present
      ansible.builtin.apt:
        name:
          - yamllint
          - ansible-lint
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure markdown stuff is present
      ansible.builtin.apt:
        name:
          - mdformat
        update_cache: true
        cache_valid_time: 3600
