---
- name: Install cups (I should really don't use this...)
  become: "{{ cups_become_admin }}"
  become_user: "{{ cups_become_admin_user }}"
  block:

  - name: Install dependencies.
    ansible.builtin.apt:
      name:
        - cups
        - printer-driver-escpr
      update_cache: true
      cache_valid_time: 3600
    tags: apt

  - name: Ensure cups-browsed is not installed.
    ansible.builtin.apt:
      name:
        - cups-browsed
      state: absent

  - name: Ensure cups is stopped and disabled
    ansible.builtin.systemd:
      name: cups
      enabled: false
      state: stopped

  - name: Add {{ cups_become_user }} to lp and lpadmin groups
    ansible.builtin.user:
      name: "{{ cups_become_user }}"
      groups: lp,lpadmin
      append: true
