---

- block:

    - name: ensure KVM and libvirt related stuff are present
      ansible.builtin.apt:
        name:
          - libvirt-daemon-system
          - qemu-system
          - virt-manager
          - virtiofsd
        update_cache: true
        cache_valid_time: 3600


  become: "{{ kvm_become }}"
  become_user: "{{ kvm_become_user }}"
