---
- name: Setup virtualization stuff.
  become: "{{ kvm_become }}"
  become_user: "{{ kvm_become_user }}"
  block:

    - name: Ensure KVM, libvirt and Incus related stuff are present
      ansible.builtin.apt:
        name:
          - incus
          - libvirt-daemon-system
          - qemu-system
          - vagrant
          - vagrant-libvirt
          - virt-manager
          - virtiofsd
        update_cache: true
        cache_valid_time: 3600

    - name: Use nftables in libvirt network.conf
      ansible.builtin.lineinfile:
        path: /etc/libvirt/network.conf
        regexp: "^#?firewall_backend"
        line: 'firewall_backend = "nftables"'

    - name: Add to incus-admin group {{ kvm_user }}
      ansible.builtin.user:
        name: "{{ kvm_user }}"
        groups: incus-admin
        append: true
