---
- name: Setup virtualization stuff.
  become: "{{ kvm_become }}"
  become_user: "{{ kvm_become_user }}"
  block:

    - name: Ensure KVM and libvirt related stuff are present
      ansible.builtin.apt:
        name:
          - libvirt-daemon-system
          - qemu-system
          - vagrant
          - vagrant-libvirt
          - virt-manager
          - virtiofsd
        update_cache: true
        cache_valid_time: 3600

    - name: Use nftables in libvirt network.conf
      ansible.builtin.lineinfile:
        path: /etc/libvirt/network.conf
        regexp: "^#?firewall_backend"
        line: 'firewall_backend = "nftables"'
