---

- block:
    - name: install source.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ testing main contrib non-free-firmware non-free
          deb-src http://deb.debian.org/debian/ testing main contrib non-free-firmware non-free
          deb http://deb.debian.org/debian/ unstable main contrib non-free-firmware non-free
          deb-src http://deb.debian.org/debian/ unstable main contrib non-free-firmware non-free
          deb http://deb.debian.org/debian/ experimental main contrib non-free-firmware non-free
          # deb-src http://deb.debian.org/debian/ experimental main contrib non-free

          # deb http://deb.debian.org/debian-debug/ testing-debug main
          # deb http://deb.debian.org/debian-debug/ testing-proposed-updates-debug main
          # deb http://deb.debian.org/debian-debug/ unstable-debug main
          # deb http://deb.debian.org/debian-debug/ experimental-debug main

          # Line commented out by installer because it failed to verify:
          # deb http://security.debian.org/debian-security/ bullseye/updates main
          # Line commented out by installer because it failed to verify:
          # deb-src http://security.debian.org/debian-security/ bullseye/updates main

    - name: install source.list
      ansible.builtin.copy:
        dest: /etc/apt/preferences
        content: |
          Package: *
          Pin: release a=testing
          Pin-Priority: 900

          Package: *
          Pin: release o=Debian
          Pin-Priority: -1

  become: "{{ apt_become }}"
  become_user: "{{ apt_become_user }}"
