---

- block:

    - name: ensure video stuff is present
      ansible.builtin.apt:
        name:
          - dragonplayer
          - ffmpeg
          # - obs-studio
          - v4l2loopback-dkms
          - vlc
          - yt-dlp

  become: "{{ video_become }}"
  become_user: "{{ video_become_user }}"
