---

- block:

    - name: ensure TeX is installed
      ansible.builtin.apt:
        name:
          - texlive-base
          - texlive-extra-utils
          - texlive-games
          - texlive-humanities
          - texlive-lang-greek
          - texlive-lang-italian
          - texlive-latex-base
          - texlive-latex-extra
          - texlive-luatex
          - texlive-pictures
          - texlive-plain-generic
          - texlive-pstricks
          - texlive-science
        update_cache: true
        cache_valid_time: 3600

  become: "{{ tex_become }}"
  become_user: "{{ tex_become_user }}"
