---

- name: install vdirsyncer
  ansible.builtin.apt:
    name: vdirsyncer
    update_cache: true
    cache_valid_time: 3600
  tags: apt

  become: "{{ vdirsyncer_become_admin }}"
  become_user: "{{ vdirsyncer_become_admin_user }}"

- block:

  - name: ensure directories for vdirsyncer exists
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - ~/.config/vdirsyncer
      - ~/.cache/vdirsyncer/status
      - ~/.local/share/vdirsyncer/contacts
      - ~/.local/share/vdirsyncer/calendars

  - name: copy vdirsyncer config file
    ansible.builtin.copy:
      content: "{{ vdirsyncer_config }}"
      dest: ~/.config/vdirsyncer/config

  - name: ensure ~/.config/systemd/user exists
    ansible.builtin.file:
      path: ~/.config/systemd/user
      state: directory

  - name: install vdirsyncer systemd user unit file
    ansible.builtin.copy:
      src: config/systemd/user/vdirsyncer.service
      dest: ~/.config/systemd/user/vdirsyncer.service
    notify:
      - systemctl user daemon-reload

  - name: install vdirsyncer systemd user timer file
    ansible.builtin.copy:
      src: config/systemd/user/vdirsyncer.timer
      dest: ~/.config/systemd/user/vdirsyncer.timer
    notify:
      - systemctl user daemon-reload

  - name: systemctl user start and enable vdirsyncer timer
    systemd:
      scope: user
      name: vdirsyncer.timer
      enabled: true
      state: started

  become: "{{ vdirsyncer_become }}"
  become_user: "{{ vdirsyncer_become_user }}"
