---

- block:

    - name: ensure libreoffice programs are present
      ansible.builtin.apt:
        name:
          - hunspell-it
          - libreoffice-calc
          - libreoffice-draw
          - libreoffice-impress
          - libreoffice-l10n-it
          - libreoffice-math
          - libreoffice-plasma
          - libreoffice-style-breeze
          - libreoffice-writer
        update_cache: true
        cache_valid_time: 3600

    - name: ensure PDF stuff is present
      ansible.builtin.apt:
        name:
          - xournalpp
          - evince
          - pdftk-java
          - zathura
        update_cache: true
        cache_valid_time: 3600

    - name: ensure ebook stuff is present
      ansible.builtin.apt:
        name:
          - calibre
        update_cache: true
        cache_valid_time: 3600


  become: "{{ office_become }}"
  become_user: "{{ office_become_user }}"
