---
- name: Install office related stuff
  become: "{{ office_become }}"
  become_user: "{{ office_become_user }}"
  block:
    - name: Ensure libreoffice programs are present
      ansible.builtin.apt:
        name:
          - hunspell-it
          - libreoffice-calc
          - libreoffice-draw
          - libreoffice-impress
          - libreoffice-l10n-it
          - libreoffice-math
          - libreoffice-plasma
          - libreoffice-style-breeze
          - libreoffice-writer
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure PDF stuff is present
      ansible.builtin.apt:
        name:
          - xournalpp
          - evince
          - pdftk-java
          - zathura
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure document conversion tools are present
      ansible.builtin.apt:
        name:
          - pandoc
          - wkhtmltopdf
        update_cache: true
        cache_valid_time: 3600

    - name: Ensure ebook stuff is present
      ansible.builtin.apt:
        name:
          - calibre
        update_cache: true
        cache_valid_time: 3600
