---

- block:

    - name: ensure nvidia-driver is present
      ansible.builtin.apt:
        name:
          # - nvidia-detect  # Needed only to detect the driver to use.
          - nvidia-driver
          - nvidia-cuda-dev
          - nvidia-cuda-toolkit


  become: "{{ apt_become }}"
  become_user: "{{ apt_become_user }}"
