---
bun_become: true
bun_become_user: "{{ lookup('env', 'USER') }}"

bun_version: 1.4.0
bun_tarball: bun-linux-x64.zip
bun_download_url: "https://github.com/oven-sh/bun/releases/download/bun-v{{ bun_version }}/{{ bun_tarball }}"
bun_tarball_sha256: 2d03fb5fb83ac8b567aca0a281b2ce1a1a19d488f56c2968d88c3f25e92fe452
