---

- block:

    - name: ensure packagekit and appstream are absent
      ansible.builtin.apt:
        name:
          - packagekit
          - appstream
        state: absent

    - name: ensure systemd.conf.d exists
      ansible.builtin.file:
        dest: /etc/systemd/system.conf.d/
        state: directory
        mode: 0755

    - name: ensure short systemd timeout
      ansible.builtin.copy:
        dest: /etc/systemd/system.conf.d/timeouts.conf
        content: |
          [Manager]
          DefaultTimeoutStopSec=15s
          DefaultTimeoutAbortSec=15s
        mode: 0644

    - name: ensure nano and rpcbind are absent
      ansible.builtin.apt:
        name:
          - nano
          - rpcbind
        state: absent

    - name: ensure fwupd is present
      ansible.builtin.apt:
        name:
          - fwupd
          - fwupd-amd64-signed
        update_cache: true
        cache_valid_time: 3600

    - name: ensure archive tools are present
      ansible.builtin.apt:
        name:
          - zip
          - gzip
          - bzip2
          - lz4
          - pbzip2
          - unrar
        update_cache: true
        cache_valid_time: 3600

    - name: ensure terminal tools are present
      ansible.builtin.apt:
        name:
          - bat
          - fd-find
          - fzf
          - moreutils
          - neofetch
          - neovim
          - pv
          - ripgrep
        update_cache: true
        cache_valid_time: 3600

    - name: ensure monitoring tools are present
      ansible.builtin.apt:
        name:
          - acpi
          - duf
          - htop
          - iftop
          - lm-sensors
          - time
          # - libbpf-tools
        update_cache: true
        cache_valid_time: 3600

    - name: ensure security tools are present
      ansible.builtin.apt:
        name:
          - apache2-utils
          - gnupg
          - minisign
          - pass
          - pass-extension-tomb
          - pinentry-qt
          - python3-keyring
        update_cache: true
        cache_valid_time: 3600

    - name: ensure specific fonts are present
      ansible.builtin.apt:
        name:
          - fonts-hack
          - fonts-texgyre
          - fonts-texgyre-math
        update_cache: true
        cache_valid_time: 3600

    - name: ensure sync tools are present
      ansible.builtin.apt:
        name:
          - git-annex
        update_cache: true
        cache_valid_time: 3600

    - name: ensure 3D tools are present
      ansible.builtin.apt:
        name:
          - mesa-utils
        update_cache: true
        cache_valid_time: 3600

    - name: ensure radeontop is present in AMD machines
      ansible.builtin.apt:
        name: radeontop
      when: "'AuthenticAMD' in ansible_facts.processor"

  become: "{{ system_become }}"
  become_user: "{{ system_become_user }}"
