---
- name: install git
  ansible.builtin.apt:
    name:
      - git
      - git-cola
      - git-filter-repo
      - git-lfs
    update_cache: true
    cache_valid_time: 3600
  tags: apt

  become: "{{ git_become_admin }}"
  become_user: "{{ git_become_admin_user }}"

- block:

    - name: copy user .gitconfig
      ansible.builtin.copy:
        src: gitconfig
        dest: ~/.gitconfig
        mode: 0640

    - name: copy user .gitignore
      ansible.builtin.copy:
        src: gitignore
        dest: ~/.gitignore
        mode: 0640

    - name: set .gitconfig.local
      ansible.builtin.copy:
        content: "{{ git_config_local }}"
        dest: ~/.gitconfig.local
        mode: 0640

  become: "{{ git_become }}"
  become_user: "{{ git_become_user }}"
