---

- name: install emacs
  apt:
    name:
      - emacs
      - emacs-gtk
      - libtext-multimarkdown-perl  # For multimarkdown.
      - build-essential  # For org-roam.
      - fonts-firacode
    update_cache: true
    cache_valid_time: 3600

  become: "{{ emacs_become_admin }}"
  become_user: "{{ emacs_become_admin_user }}"

- block:
    - name: ensure ~/.emacs.d and subfolders exist
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - ~/.emacs.d
        - "{{ emacs_org_roam_directory }}/daily"
        - "{{ emacs_org_roam_directory }}/projects"

    - name: copy init.el into ~/.emacs.d
      template:
        src: emacs.d/init.el.j2
        dest: ~/.emacs.d/init.el
        owner: "{{ emacs_become_user }}"
        group: "{{ emacs_become_user }}"
        mode: 0640

    - name: ensure {{ emacs_org_roam_directory }} exists
      file:
        path: "{{ emacs_org_roam_directory }}"
        state: directory

  become: "{{ emacs_become }}"
  become_user: "{{ emacs_become_user }}"
