---
- name: Install and setup josm
  become: "{{ josm_become }}"
  become_user: "{{ josm_become_user }}"
  block:
    - name: Ensure josm is present
      ansible.builtin.apt:
        name:
          - josm
        update_cache: true
        cache_valid_time: 3600

    - name: Set scaling and fonts aliasing
      ansible.builtin.lineinfile:
        path: /etc/default/josm
        insertafter: EOF
        # yamllint disable-line rule:line-length
        line: 'JAVA_OPTS="-Dsun.java2d.uiScale=2 -Dawt.useSystemAAFontSettings=on ${JAVA_OPTS}"'
