---

- name: ensure 70-no-bitmaps.conf is disabled
  ansible.builtin.file:
    path: /etc/fonts/conf.d/70-no-bitmaps.conf
    state: absent

  become: "{{ fontconfig_become_admin }}"
  become_user: "{{ fontconfig_become_admin_user }}"

- block:
  - name: ensure ~/.config/fontconfig exists
    ansible.builtin.file:
      path: ~/.config/fontconfig
      state: directory

  - name: copy fonts config file
    ansible.builtin.copy:
      src: config/fontconfig/fonts.conf
      dest: ~/.config/fontconfig/fonts.conf

  - name: rebuild font information cache
    ansible.builtin.command: fc-cache -fr


  become: "{{ fontconfig_become }}"
  become_user: "{{ fontconfig_become_user }}"
