require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "dockerfile",
        "go",
        "html",
        "just",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "rust",
        "sql",
        "vim",
        "vimdoc",
    },
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
})
