---

- name: Install alacritty
  ansible.builtin.apt:
    name: alacritty
    update_cache: true
    cache_valid_time: 3600
  tags: apt

  become: "{{ alacritty_become_admin }}"
  become_user: "{{ alacritty_become_admin_user }}"

- block:

    - name: Ensure ~/.config/alacritty exists
      ansible.builtin.file:
        path: ~/.config/alacritty
        state: directory

    - name: Copy alacritty config file
      ansible.builtin.copy:
        src: config/alacritty/alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml

  become: "{{ alacritty_become }}"
  become_user: "{{ alacritty_become_user }}"
