---

- name: install alacritty
  ansible.builtin.apt:
    name: alacritty
    update_cache: true
    cache_valid_time: 3600
  tags: apt

  become: "{{ alacritty_become_admin }}"
  become_user: "{{ alacritty_become_admin_user }}"

- block:

    - name: ensure ~/.config/alacritty exists
      ansible.builtin.file:
        path: ~/.config/alacritty
        state: directory

    - name: copy alacritty config file
      ansible.builtin.copy:
        src: config/alacritty/alacritty.yml
        dest: ~/.config/alacritty/alacritty.yml

  become: "{{ alacritty_become }}"
  become_user: "{{ alacritty_become_user }}"
