add_newline = false

[directory]
truncation_length = 8
style = "cyan"

[git_status]
staged = '[✓](green)'

[line_break]
disabled = true

[python]
python_binary = [".venv/bin/python", "python", "python3", "python2"]
