---

- name: install stuff with go install
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  loop:
    - code.gitea.io/tea@v0.9.2
    - github.com/gopasspw/gopass-jsonapi@v1.15.14
    - github.com/gopasspw/gopass@v1.15.14
    - github.com/mikefarah/yq/v4@latest
    - golang.org/x/tools/cmd/goimports@latest

  become: "{{ go_install_become }}"
  become_user: "{{ go_install_become_user }}"
