---

- name: install stuff with go install
  ansible.builtin.shell:
    cmd: "go install {{ item }}"
  with_items:
    - github.com/gopasspw/gopass@v1.15.12
    - github.com/gopasspw/gopass-jsonapi@v1.15.12
    - code.gitea.io/tea@v0.9.2
    - golang.org/x/tools/cmd/goimports@latest

  become: "{{ go_install_become }}"
  become_user: "{{ go_install_become_user }}"
