---

- name: install stuff with go install
  ansible.builtin.command:
    cmd: "go install {{ item }}"
  loop:
    - code.gitea.io/tea@v0.9.2
    - git.sr.ht/~geb/dotool@latest
    - github.com/charmbracelet/glow@latest
    - github.com/gopasspw/gopass-jsonapi@v1.15.16
    - github.com/gopasspw/gopass@v1.15.16
    - github.com/mikefarah/yq/v4@latest
    - github.com/sinclairtarget/git-who@latest
    - golang.org/x/tools/cmd/goimports@latest

  become: "{{ go_install_become }}"
  become_user: "{{ go_install_become_user }}"
